fallback = 'ï‹'

[matching]
'anki' = { type = 'generic', value = 'ï€…'}
'/(?i)settings*/' = { type = 'generic', value = 'ï€“'}
'/(?i)calendar*/' = { type = 'generic', value = 'ï„³'}
'chromium' = 'ï‰¨'

# from https://github.com/Lyr-7D1h/swayest_workstyle/issues/16
'/Firefox .*Private Browsing/' = 'ï°'
'/(?i)Google Drive.*Firefox/' = 'ïª'
'/(?i)Google Calendar.*Firefox/' = 'ï³'
'// Twitter.*Firefox/' = 'ï‚™'
'/ eBay.*Firefox/' = 'ï“´'
'/(?i)reddit.*Firefox/' = 'ïŠ'
'/(?i)drive.*Firefox/' = 'ïª'
'/(?i)play.*Firefox/' = 'ï«'
'/(?i)Github.*Firefox/' = 'ï‚›'
'/Google.*Firefox/' = 'ï† '
'/(?i)MAX.*Iridium/' = 'ïŠ‰'
'/(?i)Dashboards -.*Iridium/' = 'ï‚€'
'/(?i) youtube.*Firefox/' = 'ï…§'
'pavucontrol' = 'ï€¨'
'foot' = 'ï„ '
'/YouTube/' = 'ï…ª'
'org.qutebrowser.qutebrowser' = 'ï’„'
'whatsapp-for-linux' = 'ïˆ²'
'Ardour-6.9.0' = 'ğŸµ'
'Pcmanfm' = 'ï„”'
'dota2' = 'âš”'
'Gimp' = 'ï‡¼'
'/pdf/' = 'ï‡'
'/docx/' = 'ï‡'

